#ifndef SOUND_H
#define SOUND_H

#include "bh.h"

#define SND_SAMPLE_ALIEN_FALL 64
#define SND_SAMPLE_ALIEN_POP 65
#define SND_SAMPLE_CANNON_FALL 66
#define SND_SAMPLE_CANNON_SHOT 67
#define SND_SAMPLE_GUY_THUNK 68
#define SND_SAMPLE_HORSE 69
#define SND_SAMPLE_JUMP 70
#define SND_SAMPLE_PAUSE 71
#define SND_SAMPLE_CREAK_1 72
#define SND_SAMPLE_CREAK_2 73
#define SND_SAMPLE_GAME_OVER 74

void snd_init(void);

#endif
