#include "bh.h"

void snd_init(void) {
    XGM_setPCM(SND_SAMPLE_SONG_1, WAV_SONG_1, sizeof(WAV_SONG_1));
    XGM_setPCM(SND_SAMPLE_ALIEN_FALL, WAV_ALIEN_FALL, sizeof(WAV_ALIEN_FALL));
    XGM_setPCM(SND_SAMPLE_ALIEN_POP, WAV_ALIEN_POP, sizeof(WAV_ALIEN_POP));
    XGM_setPCM(SND_SAMPLE_CANNON_FALL, WAV_CANNON_FALL, sizeof(WAV_CANNON_FALL));
    XGM_setPCM(SND_SAMPLE_CANNON_SHOT, WAV_CANNON_SHOT, sizeof(WAV_CANNON_SHOT));
    XGM_setPCM(SND_SAMPLE_GUY_THUNK, WAV_GUY_THUNK, sizeof(WAV_GUY_THUNK));
    XGM_setPCM(SND_SAMPLE_HORSE, WAV_HORSE, sizeof(WAV_HORSE));
    XGM_setPCM(SND_SAMPLE_JUMP, WAV_JUMP, sizeof(WAV_JUMP));
    XGM_setPCM(SND_SAMPLE_PAUSE, WAV_PAUSE, sizeof(WAV_PAUSE));
    XGM_setPCM(SND_SAMPLE_CREAK_1, WAV_CREAK_1, sizeof(WAV_CREAK_1));
    XGM_setPCM(SND_SAMPLE_CREAK_2, WAV_CREAK_2, sizeof(WAV_CREAK_2));
    XGM_setPCM(SND_SAMPLE_GAME_OVER, WAV_GAME_OVER, sizeof(WAV_GAME_OVER));
}
